package view;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;
import controller.ClienteDao;
import main.Principal;
import util.Alexa;


public class CadCliente extends javax.swing.JFrame {

        
    
    public CadCliente() {
        
          initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCelular = new javax.swing.JFormattedTextField();
        jCpf = new javax.swing.JFormattedTextField();
        jData = new javax.swing.JFormattedTextField();
        jFone = new javax.swing.JFormattedTextField();
        jCodigo = new javax.swing.JTextField();
        jRg = new javax.swing.JTextField();
        jEnd = new javax.swing.JTextField();
        jBairro = new javax.swing.JTextField();
        JEmail = new javax.swing.JTextField();
        jNome = new javax.swing.JTextField();
        jCidade = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButtonInativar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(966, 606));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            jCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCelularActionPerformed(evt);
            }
        });
        getContentPane().add(jCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 230, -1));

        try {
            jCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));

        jData.setText("  /  /    ");
        getContentPane().add(jData, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        try {
            jFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoneActionPerformed(evt);
            }
        });
        getContentPane().add(jFone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, -1));
        getContentPane().add(jCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, -1));
        getContentPane().add(jRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 230, -1));
        getContentPane().add(jEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 690, -1));
        getContentPane().add(jBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 230, -1));
        getContentPane().add(JEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 230, -1));

        jNome.setToolTipText("");
        jNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 430, -1));
        getContentPane().add(jCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 230, -1));

        jButtonCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCadastrar.setText("CADASTRAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        jButtonAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAtualizar.setText("ATUALIZAR");
        jButtonAtualizar.setPreferredSize(new java.awt.Dimension(111, 27));
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("BAIRRO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jButtonInativar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonInativar.setText("INATIVAR");
        jButtonInativar.setPreferredSize(new java.awt.Dimension(111, 27));
        jButtonInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInativarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInativar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, -1, -1));

        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(111, 27));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("E-MAIL");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("TELEFONE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("RG");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("CÓDIGO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Quartz", 0, 48)); // NOI18N
        jLabel7.setText("Cadastro de clientes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("NOME");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("CPF");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 40, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("ENDEREÇO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("CELULAR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("DATA NASC.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("CIDADE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 966, 606));
        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFoneActionPerformed

    private void jCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCelularActionPerformed

    private void jNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeActionPerformed

    private void jCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCpfActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        if (jNome.getText().matches("")|| jCpf.getText().matches("")){
            Alexa.escrevaJanela("Preencha os campos NOME e CPF!");
        }else{
        
        Principal.cliente.setNomeCliente(jNome.getText());
        Principal.cliente.setCpfCliente(jCpf.getText());
        Principal.cliente.setRgCliente(jRg.getText());
        Principal.cliente.setDtnCliente(jData.getText());
        Principal.cliente.setEmailCliente(JEmail.getText());
        Principal.cliente.setFoneCliente(jFone.getText());
        Principal.cliente.setCelularCliente(jCelular.getText());
        Principal.cliente.setEndCliente(jEnd.getText());
        Principal.cliente.setBairroCliente(jBairro.getText());
        Principal.cliente.setCidCliente(jCidade.getText());
        
        
        boolean cadastrou = Principal.clienteDao.inserir(Principal.cliente);
        if (cadastrou) {
            Alexa.escrevaJanela("Cliente cadastrado com sucesso!");
            limparCampos();
        }else{
            Alexa.escrevaJanela("Falha ao cadastrar cliente!");
        }
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
              
        Principal.cliente.setIdCliente(Integer.parseInt(jCodigo.getText()));
        Principal.cliente = Principal.clienteDao.buscar(Principal.cliente.getIdCliente());
        if (Principal.cliente == null || Principal.cliente.getNomeCliente() == null){
            Alexa.escrevaJanela("Nenhum cliente encontrado com este código!");
        }else{
            jNome.setText(Principal.cliente.getNomeCliente());
            jCpf.setText(Principal.cliente.getCpfCliente());
            jRg.setText(Principal.cliente.getRgCliente());
            jData.setText(Principal.cliente.getDtnCliente());
            JEmail.setText(Principal.cliente.getEmailCliente());
            jFone.setText(Principal.cliente.getFoneCliente());
            jCelular.setText(Principal.cliente.getCelularCliente());
            jEnd.setText(Principal.cliente.getEndCliente());
            jBairro.setText(Principal.cliente.getBairroCliente());
            jCidade.setText(Principal.cliente.getCidCliente());
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        if (jNome.getText().matches("")|| jCpf.getText().matches("")){
            Alexa.escrevaJanela("Preencha os campos NOME e CPF!");
        }else{
        
        Principal.cliente.setIdCliente(Integer.parseInt(jCodigo.getText()));
        Principal.cliente.setNomeCliente(jNome.getText());
        Principal.cliente.setCpfCliente(jCpf.getText());
        Principal.cliente.setRgCliente(jRg.getText());
        Principal.cliente.setDtnCliente(jData.getText());
        Principal.cliente.setEmailCliente(JEmail.getText());
        Principal.cliente.setFoneCliente(jFone.getText());
        Principal.cliente.setCelularCliente(jCelular.getText());
        Principal.cliente.setEndCliente(jEnd.getText());
        Principal.cliente.setBairroCliente(jBairro.getText());
        Principal.cliente.setCidCliente(jCidade.getText());
        
        boolean cadastrou = Principal.clienteDao.atualizar(Principal.cliente);
        if (cadastrou){
            Alexa.escrevaJanela("Cliente atualizado com sucesso!");
            limparCampos();
        }else{
            Alexa.escrevaJanela("Falha ao cadastrar o cliente!");
        }
    }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInativarActionPerformed
        // TODO add your handling code here:
        Principal.cliente.setIdCliente(Integer.parseInt(jCodigo.getText()));
        boolean inativar = Principal.clienteDao.inativar(Principal.cliente.getIdCliente());
        if (inativar) {
            Alexa.escrevaJanela("Cliente inativado com sucesso!");
            limparCampos();
        } else {
            Alexa.escrevaJanela("Cliente não encontrado!");
        }
    }//GEN-LAST:event_jButtonInativarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JEmail;
    private javax.swing.JTextField jBairro;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonInativar;
    private javax.swing.JFormattedTextField jCelular;
    private javax.swing.JTextField jCidade;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JFormattedTextField jCpf;
    private javax.swing.JFormattedTextField jData;
    private javax.swing.JTextField jEnd;
    private javax.swing.JFormattedTextField jFone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jRg;
    // End of variables declaration//GEN-END:variables

private void limparCampos() {
    jCodigo.setText("");
    jNome.setText("");
    jCpf.setText("");
    jRg.setText("");
    jData.setText("");
    JEmail.setText("");
    jFone.setText("");
    jCelular.setText("");
    jEnd.setText("");
    jBairro.setText("");
    jCidade.setText("");
}
}
