package view;

import javax.swing.JRadioButton;
import main.Principal;
import util.Alexa;

/**
 *
 * @author deko_
 */
public class CadColab extends javax.swing.JFrame {

    /**
     * Creates new form CadColab
     */
    public CadColab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCodcolab = new javax.swing.JTextField();
        jLogincolab = new javax.swing.JTextField();
        jSenhacolab = new javax.swing.JTextField();
        jNomecolab = new javax.swing.JTextField();
        jRadioButtonAdmin = new javax.swing.JRadioButton();
        jRadioButtonUser = new javax.swing.JRadioButton();
        jButtonCadcolab = new javax.swing.JButton();
        jButtonattcolab = new javax.swing.JButton();
        jButtonBusccolab = new javax.swing.JButton();
        jButtonInativacolab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Quartz", 0, 40)); // NOI18N
        jLabel7.setText("Cadastro de colaborador");

        jLabel1.setText("CÓDIGO");

        jLabel2.setText("LOGIN");

        jLabel3.setText("SENHA");

        jLabel4.setText("NOME");

        jLabel5.setText("NÍVEL");

        jCodcolab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodcolabActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonAdmin);
        jRadioButtonAdmin.setText("ADMINISTRADOR");
        jRadioButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonUser);
        jRadioButtonUser.setText("USUÁRIO");

        jButtonCadcolab.setText("CADASTRAR");
        jButtonCadcolab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadcolabActionPerformed(evt);
            }
        });

        jButtonattcolab.setText("ATUALIZAR");
        jButtonattcolab.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonattcolab.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonattcolab.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonattcolab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonattcolabActionPerformed(evt);
            }
        });

        jButtonBusccolab.setText("BUSCAR");
        jButtonBusccolab.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonBusccolab.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonBusccolab.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonBusccolab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusccolabActionPerformed(evt);
            }
        });

        jButtonInativacolab.setText("INATIVAR");
        jButtonInativacolab.setMaximumSize(new java.awt.Dimension(97, 23));
        jButtonInativacolab.setMinimumSize(new java.awt.Dimension(97, 23));
        jButtonInativacolab.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonInativacolab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInativacolabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadcolab)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLogincolab)
                                .addComponent(jSenhacolab)
                                .addComponent(jNomecolab)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCodcolab, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonAdmin)
                                            .addGap(41, 41, 41))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jButtonattcolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBusccolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                    .addComponent(jButtonInativacolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCodcolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLogincolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSenhacolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jNomecolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonAdmin)
                        .addComponent(jRadioButtonUser)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadcolab)
                    .addComponent(jButtonattcolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBusccolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInativacolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCodcolabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodcolabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodcolabActionPerformed

    private void jButtonCadcolabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadcolabActionPerformed
        // TODO add your handling code here:
        if (jLogincolab.getText().matches("") || jSenhacolab.getText().matches("") || jNomecolab.getText().matches("") || (!jRadioButtonAdmin.isSelected() && !jRadioButtonUser.isSelected())) {
            Alexa.escrevaJanela("Verifique se os campos LOGIN, SENHA e NOME estão preenchidos e selecione o nível do usuário!");
        } else {
            Principal.colaborador.setIdLogin(jLogincolab.getText());
            Principal.colaborador.setIdSenha(jSenhacolab.getText());
            Principal.colaborador.setNomeUser(jNomecolab.getText());

            if (jRadioButtonAdmin.isSelected()) {
                Principal.colaborador.setUserNivel(1);
            } else if (jRadioButtonUser.isSelected()) {
                Principal.colaborador.setUserNivel(2);
            }

            boolean cadastrou = Principal.colaboradorDao.inserir(Principal.colaborador);
            if (cadastrou) {
                Alexa.escrevaJanela("Colaborador cadastrado com sucesso!");
                limparCampos();
            } else {
                Alexa.escrevaJanela("Falha ao cadastrar colaborador!");
            }
        }

    }//GEN-LAST:event_jButtonCadcolabActionPerformed

    private void jButtonattcolabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonattcolabActionPerformed
        // TODO add your handling code here:
        if (jLogincolab.getText().matches("") || jSenhacolab.getText().matches("") || jNomecolab.getText().matches("") || (!jRadioButtonAdmin.isSelected() && !jRadioButtonUser.isSelected())) {
            Alexa.escrevaJanela("Verifique se os campos LOGIN, SENHA e NOME estão preenchidos e selecione o nível do usuário!");
        } else {

            Principal.colaborador.setIdUser(Integer.parseInt(jCodcolab.getText()));
            Principal.colaborador.setIdLogin(jLogincolab.getText());
            Principal.colaborador.setIdSenha(jSenhacolab.getText());
            Principal.colaborador.setNomeUser(jNomecolab.getText());

            if (jRadioButtonAdmin.isSelected()) {
                Principal.colaborador.setUserNivel(1);
            } else if (jRadioButtonUser.isSelected()) {
                Principal.colaborador.setUserNivel(2);
            }

            boolean cadastrou = Principal.colaboradorDao.atualizar(Principal.colaborador);
            if (cadastrou) {
                Alexa.escrevaJanela("Colaborador atualizado com sucesso!");
                limparCampos();
            } else {
                Alexa.escrevaJanela("Falha ao atualizar o colaborador!");
            }
        }
    }//GEN-LAST:event_jButtonattcolabActionPerformed

    private void jRadioButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAdminActionPerformed

    private void jButtonBusccolabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusccolabActionPerformed
        // TODO add your handling code here:
        Principal.colaborador.setIdUser(Integer.parseInt(jCodcolab.getText()));
        Principal.colaborador = Principal.colaboradorDao.buscar(Principal.colaborador.getIdUser());

        if (Principal.colaborador == null || Principal.colaborador.getNomeUser() == null) {
            Alexa.escrevaJanela("Nenhum colaborador encontrado com este código!");
        } else {
            jLogincolab.setText(Principal.colaborador.getIdLogin());
            jSenhacolab.setText(Principal.colaborador.getIdSenha());
            jNomecolab.setText(Principal.colaborador.getNomeUser());

            if (Principal.colaborador.getUserNivel() == 1) {
                jRadioButtonAdmin.setSelected(true);
            } else if (Principal.colaborador.getUserNivel() == 2) {
                jRadioButtonUser.setSelected(true);
            }
        }
    }//GEN-LAST:event_jButtonBusccolabActionPerformed

    private void jButtonInativacolabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInativacolabActionPerformed
        // TODO add your handling code here:
        Principal.colaborador.setIdUser(Integer.parseInt(jCodcolab.getText()));
        boolean inativar = Principal.colaboradorDao.inativar(Principal.colaborador.getIdUser());
        if (inativar) {
            Alexa.escrevaJanela("Colaborador inativado com sucesso!");
            limparCampos();
        } else {
            Alexa.escrevaJanela("Colaborador não encontrado!");
        }
    }//GEN-LAST:event_jButtonInativacolabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadColab.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadColab.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadColab.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadColab.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editojButtonCadcolab
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadColab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBusccolab;
    private javax.swing.JButton jButtonCadcolab;
    private javax.swing.JButton jButtonInativacolab;
    private javax.swing.JButton jButtonattcolab;
    private javax.swing.JTextField jCodcolab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jLogincolab;
    private javax.swing.JTextField jNomecolab;
    private javax.swing.JRadioButton jRadioButtonAdmin;
    private javax.swing.JRadioButton jRadioButtonUser;
    private javax.swing.JTextField jSenhacolab;
    // End of variables declaration//GEN-END:variables
private void limparCampos() {
        jCodcolab.setText("");
        jLogincolab.setText("");
        jSenhacolab.setText("");
        jNomecolab.setText("");

    }

}
