package view;

import main.Principal;
import util.Alexa;

/**
 *
 * @author deko_
 */
public class CadProced extends javax.swing.JFrame {

    /**
     * Creates new form CadProced
     */
    public CadProced() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCodpro = new javax.swing.JTextField();
        jNomepro = new javax.swing.JTextField();
        jValorpro = new javax.swing.JTextField();
        jButtonCadpro = new javax.swing.JButton();
        jButtonAttpro = new javax.swing.JButton();
        jButtonBuscpro = new javax.swing.JButton();
        jButtonInapro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Quartz", 0, 40)); // NOI18N
        jLabel7.setText("Cadastro de procedimentos");

        jLabel1.setText("CÓDIGO");

        jLabel2.setText("NOME");

        jLabel3.setText("VALOR");

        jButtonCadpro.setText("CADASTRAR");
        jButtonCadpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadproActionPerformed(evt);
            }
        });

        jButtonAttpro.setText("ATUALIZAR");
        jButtonAttpro.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonAttpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttproActionPerformed(evt);
            }
        });

        jButtonBuscpro.setText("BUSCAR");
        jButtonBuscpro.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonBuscpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscproActionPerformed(evt);
            }
        });

        jButtonInapro.setText("INATIVAR");
        jButtonInapro.setPreferredSize(new java.awt.Dimension(97, 23));
        jButtonInapro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInaproActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jValorpro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCodpro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNomepro)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonCadpro)
                            .addGap(35, 35, 35)
                            .addComponent(jButtonAttpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(jButtonBuscpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(jButtonInapro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addComponent(jCodpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jNomepro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jValorpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadpro)
                    .addComponent(jButtonAttpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInapro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadproActionPerformed
        // TODO add your handling code here:
        if (jNomepro.getText().matches("") || jValorpro.getText().matches("")) {
            Alexa.escrevaJanela("Preencha o campo NOME e o campo VALOR!");
        } else {

            Principal.procedimento.setNomeProcedimento(jNomepro.getText());
            Principal.procedimento.setValorProcedimento(jValorpro.getText());

            boolean cadastrou = Principal.procedimentoDao.inserir(Principal.procedimento);
            if (cadastrou) {
                Alexa.escrevaJanela("Procedimento cadastrado com sucesso!");
                limparCampos();
            } else {
                Alexa.escrevaJanela("Falha ao cadastrar procedimento!");
            }
        }
    }//GEN-LAST:event_jButtonCadproActionPerformed

    private void jButtonAttproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttproActionPerformed
        // TODO add your handling code here:
        if (jNomepro.getText().matches("") || jValorpro.getText().matches("")) {
            Alexa.escrevaJanela("Preencha os campos NOME e VALOR!");
        } else {
            Principal.procedimento.setIdProcedimento(Integer.parseInt(jCodpro.getText()));
            Principal.procedimento.setNomeProcedimento(jNomepro.getText());
            Principal.procedimento.setValorProcedimento(jValorpro.getText());

            boolean cadastrou = Principal.procedimentoDao.atualizar(Principal.procedimento);
            if (cadastrou) {
                Alexa.escrevaJanela("Procedimento atualizado com sucesso!");
                limparCampos();
            } else {
                Alexa.escrevaJanela("Falha ao atualizar o procedimento!");
            }
        }
    }//GEN-LAST:event_jButtonAttproActionPerformed

    private void jButtonBuscproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscproActionPerformed
        // TODO add your handling code here:
        Principal.procedimento.setIdProcedimento(Integer.parseInt(jCodpro.getText()));
        Principal.procedimento = Principal.procedimentoDao.buscar(Principal.procedimento.getIdProcedimento());
        if (Principal.procedimento == null || Principal.procedimento.getNomeProcedimento() == null){
            Alexa.escrevaJanela("Nenhum prodecimento encontrado com este código!");
        }else{
            jNomepro.setText(Principal.procedimento.getNomeProcedimento());
            jValorpro.setText(Principal.procedimento.getValorProcedimento());
        }
    }//GEN-LAST:event_jButtonBuscproActionPerformed

    private void jButtonInaproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInaproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInaproActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProced().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAttpro;
    private javax.swing.JButton jButtonBuscpro;
    private javax.swing.JButton jButtonCadpro;
    private javax.swing.JButton jButtonInapro;
    private javax.swing.JTextField jCodpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNomepro;
    private javax.swing.JTextField jValorpro;
    // End of variables declaration//GEN-END:variables
private void limparCampos() {
        jCodpro.setText("");
        jNomepro.setText("");
        jValorpro.setText("");
    }
}
